name: Pull & Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy-dev:
    # if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Deploy NodeJS App to DigitalOcean
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd /mnt/trade-risk
            git pull origin main
            npm install
            npm run build
            pm2 restart apis-trade-risk
